### ISSUE TITLE
With the yara_zip_module it is currently not possible to compile yara 

### ISSUE THREAD

**Issue by RHSvof** [stoerchl/yara_zip_module#1]
I tried to include the ZIP module in the current version of Yara, unfortunately I get error messages that I can't get resolved.

Here are the error messages: 
Making all in libyara
make[1]: Verzeichnis „/home/it17/Downloads/yara-master/libyara“ wird betreten
make  all-am
make[2]: Verzeichnis „/home/it17/Downloads/yara-master/libyara“ wird betreten
  CC       modules/zip.lo
modules/zip.c: In function ‘unpack’:
modules/zip.c:37:39: warning: implicit declaration of function ‘scan_context’; did you mean ‘yr_scan_context’? [-Wimplicit-function-declaration]
   37 |     YR_SCAN_CONTEXT* module_context = scan_context();
      |                                       ^~~~~~~~~~~~
      |                                       yr_scan_context
modules/zip.c:37:39: warning: initialization of ‘YR_SCAN_CONTEXT *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
In file included from modules/zip.c:30:
modules/zip.c:54:24: error: ‘UNDEFINED’ undeclared (first use in this function); did you mean ‘OP_DEFINED’?
   54 |         return_integer(UNDEFINED);
      |                        ^~~~~~~~~
./include/yara/modules.h:253:35: note: in definition of macro ‘return_integer’
  253 |     return yr_object_set_integer((integer), __function_obj->return_obj, NULL); \
      |                                   ^~~~~~~
modules/zip.c:54:24: note: each undeclared identifier is reported only once for each function it appears in
   54 |         return_integer(UNDEFINED);
      |                        ^~~~~~~~~
./include/yara/modules.h:253:35: note: in definition of macro ‘return_integer’
  253 |     return yr_object_set_integer((integer), __function_obj->return_obj, NULL); \
      |                                   ^~~~~~~
modules/zip.c:87:1: warning: control reaches end of non-void function [-Wreturn-type]
   87 | }
      | ^
make[2]: *** [Makefile:992: modules/zip.lo] Fehler 1
make[2]: Verzeichnis „/home/it17/Downloads/yara-master/libyara“ wird verlassen
make[1]: *** [Makefile:619: all] Fehler 2
make[1]: Verzeichnis „/home/it17/Downloads/yara-master/libyara“ wird verlassen
make: *** [Makefile:1201: all-recursive] Fehler 1

Thanks for help
Kind regards
René

**Comment by stoerchl** [comment]
Hi. Thanks for reaching out.
Yara renamed a few constants and functions which needed to be adapted in the ZIP module to make it work.
I updated the module. Should be working now.
