### ISSUE TITLE
Is regex-like matching possible

### ISSUE THREAD

**Issue by tatsuiman** [stoerchl/yara_zip_module#3]
I would like to write the following rule when the path of the upper hierarchy of the zip file cannot be guessed.
Is there a regex or alternative solution?

```
import "zip"

rule embedded_html
{
    meta:
    author = "@stoerchl"
    info = "searches for a given string inside a zip file"
  
    condition:
        zip.has_string(".*/index.html", "wp15:webVideoPr") > 0
}
```

**Comment by stoerchl** [comment]
There is no option to use regex. I created a new branch with searches for the specified file in the whole archive. Note: This branch does only compile with the master branch from the `yara` repo. Reason stated here: https://github.com/stoerchl/yara_zip_module/issues/2

https://github.com/stoerchl/yara_zip_module/tree/search_file

You can now simply use:
```
import "zip"

rule embedded_html
{
    meta:
    author = "@stoerchl"
    info = "searches for a given string inside a zip file"
  
    condition:
        zip.has_string("index.html", "wp15:webVideoPr") > 0
}
```
